In [1]:
import numpy as np

In [2]:
benimliste = [1,2,3,4,5]
type(benimliste)

list

In [3]:
type(np.array(benimliste))

numpy.ndarray

In [5]:
arrayListem = np.array(benimliste)  # numpy array dönüşümü
arrayListem

array([1, 2, 3, 4, 5])

### MATRİS

In [7]:
matrixListem = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
np.array(matrixListem)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

### ARANGE

In [9]:
nparange = np.arange(0,10)
nparange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### ZEROS and ONES

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### LİNSPACE

In [16]:
np.linspace(0,10,3) # eşit aralıklarla boyutlandırılmış listeler oluşturur.

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,20,5) # 5 rakam seç aralarındaki mesafe eşit olsun.

array([ 0.,  5., 10., 15., 20.])

In [22]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

### EYE

In [23]:
np.eye(5) # 5x5 birim matris oluşturur.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### RANDOM

In [24]:
np.random.randn()

-2.232479819207285

In [30]:
np.random.randn()


-1.1724457385669034

In [25]:
np.random.randn(5)

array([-0.29419703, -0.25725304, -0.32204649,  0.38374294,  0.93346359])

In [31]:
np.random.randn(3,3)

array([[-0.06999939,  0.25079338,  1.880894  ],
       [ 0.05102134,  0.09953271,  0.9776538 ],
       [ 0.35223172,  1.53518268, -0.14223981]])

In [33]:
np.random.randint(1,10) # 1 ile 10 arasında rastgele bir sayı üretir. 10 dahil değil.

7

In [35]:
np.random.randint(1,50,5)

array([11, 44,  5, 40, 24])

In [44]:
randomDizi = np.random.randint(1,100,20)
randomDizi


array([45, 15,  7, 90,  1, 21, 24, 13, 58, 93, 59, 95, 59, 64, 24, 55, 10,
       50, 27, 49])

In [39]:
numpyDizisi = np.arange(30)
numpyDizisi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### NUMPY DİZİ METHODLARI

In [40]:
numpyDizisi.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [41]:
numpyDizisi.max()

29

In [45]:
randomDizi.max()

95

In [46]:
# kaçıncı indexte olduğunu bulmak için
randomDizi.argmax()# array([45, 15,  7, 90,  1, 21, 24, 13, 58, 93, 59, 95, 59, 64, 24, 55, 10, 50, 27, 49])


11

In [47]:
randomDizi.min()

1

In [49]:
randomDizi.argmin()

4

In [50]:
numpyDizisi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
numpyDizisi.shape

(30,)

In [53]:
reshapeDizisi = numpyDizisi.reshape(6,5)
reshapeDizisi.shape

(6, 5)

In [54]:
reshapeDizisi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])