In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
benimDizim[7]

7

In [4]:
benimDizim[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[4:9]

array([4, 5, 6, 7, 8])

In [6]:
benimDizim[4:9] = 700

In [7]:
benimDizim

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14])

In [8]:
benimDizim[4:9]

array([700, 700, 700, 700, 700])

In [9]:
# Yeni bir dizi oluşturduk
baskaDizi = np.arange(0,24)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
slicingDizisi = baskaDizi[4:9]

In [11]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [12]:
slicingDizisi[:] = 500
slicingDizisi

array([500, 500, 500, 500, 500])

In [13]:
baskaDizi # orjinal dizi de değişti çünkü slicingDizisi aslında baskaDizi'nin bir parçasıdır. Yani slicingDizisi'nde yapılan değişiklikler baskaDizi'yi de etkiler.

array([  0,   1,   2,   3, 500, 500, 500, 500, 500,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [14]:
# Eğer baskaDizi'den bağımsız bir dizi oluşturmak istiyorsak copy() fonksiyonunu kullanmalıyız.

In [15]:
ornekDizi = np.arange(0,24) 

In [16]:
ornekDiziKopyasi = ornekDizi.copy()
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[4:9]
ornekDiziKopyasiSlicing

array([4, 5, 6, 7, 8])

In [20]:
ornekDiziKopyasiSlicing[:] = 900

In [21]:
ornekDiziKopyasiSlicing

array([900, 900, 900, 900, 900])

In [22]:
ornekDiziKopyasi

array([  0,   1,   2,   3, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [23]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### MATRİX

In [41]:
benimListem= [[10,20,30],[40,50,60],[70,80,90]]

In [42]:
benimMatrixDizim = np.array(benimListem)

In [43]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [44]:
benimMatrixDizim[0]

array([10, 20, 30])

In [45]:
benimMatrixDizim[1][2]

60

In [46]:
benimMatrixDizim[1,2] # Bu şekilde de elemanlara ulaşabiliriz. Nupmy'ın güzelliği

60

In [47]:
benimMatrixDizim[1:,2] # 1. satırdan itibaren tüm satırların 2. elemanlarına ulaşmak için

array([60, 90])

In [48]:
benimMatrixDizim[2:,2]

array([90])

In [49]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [50]:
benimMatrixDizim[0:,0]

array([10, 40, 70])

In [51]:
benimMatrixDizim[0:,1]

array([20, 50, 80])

In [52]:
benimMatrixDizim[0:,2]

array([30, 60, 90])

In [ ]:
benimMatrixDizim[1:2,0:2] 
#1:2 → satır aralığı: sadece 1. indeksli satırı al (2 dahil değil).
# 0:2 → sütun aralığı: 0 ve 1. indeksli sütunları al.

array([[40, 50]])

In [58]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [60]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
yeniMatrix[[0,2,4]] # 0,2 ve 4. satırları getirir

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

### OPERASYONLAR

In [64]:
yeniBirDizi = np.random.randint(1,100,20)
yeniBirDizi

array([14,  2, 40, 79, 75,  7, 44, 67, 84, 65, 47, 99, 86, 62, 19, 41, 41,
       28, 46, 76])

In [65]:
yeniBirDizi > 24

array([False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [66]:
sonucDizisi = yeniBirDizi > 24

In [67]:
yeniBirDizi[sonucDizisi] # 24'ten büyük olanları dizi şeklinde getirir

array([40, 79, 75, 44, 67, 84, 65, 47, 99, 86, 62, 41, 41, 28, 46, 76])

In [68]:
sonucDizisi

array([False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [69]:
yeniBirDizi

array([14,  2, 40, 79, 75,  7, 44, 67, 84, 65, 47, 99, 86, 62, 19, 41, 41,
       28, 46, 76])

In [70]:
sonDizi= np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [72]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [73]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [74]:
sonDizi/sonDizi

C:\Users\TUF Dash F15\AppData\Local\Temp\ipykernel_11576\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
np.sqrt(sonDizi) # Karekök almak için

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [76]:
np.max(sonDizi) # En büyük elemanı getirir

23

In [77]:
np.min(sonDizi) # En küçük elemanı getirir

0