In [1]:
import numpy as np

In [3]:
numbers1 =np.random.randint(10,100,6)
numbers2 =np.random.randint(10,100,6)

In [8]:
while True:
    print('sin :',np.sin(numbers1))
    print('cos :',np.cos(numbers2))
    print('tan :',np.tan(numbers1))
    print('log :',np.log(numbers1))
    print('log10 :',np.log10(numbers2))
    print('exp :',np.exp(numbers1))
    print('sqrt :',np.sqrt(numbers2))
    print('max :',np.max(numbers1))
    print('min :',np.min(numbers2))
    print('mean :',np.mean(numbers1))
    print('median :',np.median(numbers2))
    print('std :',np.std(numbers1))
    print('var :',np.var(numbers2))
    print('sum :',np.sum(numbers1))
    break

sin : [-0.95375265 -0.42818267  0.29636858 -0.8462204  -0.76825466  0.86006941]
cos : [-0.56245385 -0.98733928 -0.6800235  -0.95765948  0.02212676 -0.66693806]
tan : [-3.17290855  0.47381472  0.31030966  1.58815308  1.20012724  1.68582537]
log : [3.8918203  3.55534806 3.63758616 3.13549422 3.87120101 4.48863637]
log10 : [1.81291336 1.61278386 1.92427929 1.20411998 1.74036269 1.60205999]
exp : [1.90734657e+21 1.58601345e+15 3.18559318e+16 9.74480345e+09
 7.01673591e+20 4.48961282e+38]
sqrt : [8.06225775 6.40312424 9.16515139 4.         7.41619849 6.32455532]
max : 89
min : 16
mean : 47.0
median : 48.0
std : 20.69621543503385
var : 457.1388888888889
sum : 282


In [11]:
mnumbers1 =numbers1.reshape(2,3)
mnumbers2 =numbers2.reshape(2,3)
while True:
    print('mnumbers1 :\n',mnumbers1)
    print('mnumbers2 :\n',mnumbers2)
    print('mnumbers1 + mnumbers2 :\n',mnumbers1 + mnumbers2)
    print('mnumbers1 - mnumbers2 :\n',mnumbers1 - mnumbers2)
    print('mnumbers1 * mnumbers2 :\n',mnumbers1 * mnumbers2)
    print('mnumbers1 / mnumbers2 :\n',mnumbers1 / mnumbers2)
    print('mnumbers1 ** 2 :\n',mnumbers1 ** 2)
    break

mnumbers1 :
 [[49 35 38]
 [23 48 89]]
mnumbers2 :
 [[65 41 84]
 [16 55 40]]
mnumbers1 + mnumbers2 :
 [[114  76 122]
 [ 39 103 129]]
mnumbers1 - mnumbers2 :
 [[-16  -6 -46]
 [  7  -7  49]]
mnumbers1 * mnumbers2 :
 [[3185 1435 3192]
 [ 368 2640 3560]]
mnumbers1 / mnumbers2 :
 [[0.75384615 0.85365854 0.45238095]
 [1.4375     0.87272727 2.225     ]]
mnumbers1 ** 2 :
 [[2401 1225 1444]
 [ 529 2304 7921]]


In [ ]:
np.vstack((mnumbers1, mnumbers2)) # Dikey birleştirme

array([[49, 35, 38],
       [23, 48, 89],
       [65, 41, 84],
       [16, 55, 40]])

In [ ]:
np.hstack((mnumbers1, mnumbers2)) # Yatay birleştirme

array([[49, 35, 38, 65, 41, 84],
       [23, 48, 89, 16, 55, 40]])

In [17]:
numbers1

array([49, 35, 38, 23, 48, 89])

In [18]:
numbers1 > 50

array([False, False, False, False, False,  True])

In [22]:
while True:
    result =numbers1 % 2 == 0
    print(numbers1)
    print(result)
    print('Çift sayılar :',numbers1[result])
    break

[49 35 38 23 48 89]
[False False  True False  True False]
Çift sayılar : [38 48]
