In [2]:
import numpy as np

In [3]:
array = np.array([10, 15, 30, 45, 60])
array

array([10, 15, 30, 45, 60])

In [5]:
array1 = np.arange(5,15)
array1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
array2 = np.arange(50,100,5)
array2

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [7]:
array3 = np.zeros(10)
array3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
array4 = np.ones(10)
array4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
array5 = np.linspace(0,100,5)
array5

array([  0.,  25.,  50.,  75., 100.])

In [10]:
array6 = np.random.randint(10,30,5)
array6

array([22, 25, 17, 10, 14])

In [ ]:
array7 = np.random.randn(10) # -1 ile 1 arasinda 10 sayi
array7

array([ 0.97167574, -1.20597009,  1.21745851,  0.96884781,  1.64662459,
        0.98393229,  0.40009869,  0.54140021,  0.58720585,  0.82919722])

In [18]:
array8 = np.random.randint(10,50,15).reshape(3, 5)
array8

array([[15, 38, 35, 47, 43],
       [10, 43, 27, 25, 34],
       [12, 46, 25, 40, 31]])

In [21]:
matris = np.random.randint(10,50,15).reshape(3, 5)
while True:
    satirToplam = matris.sum(axis=1) # satirlarin toplami
    sutunToplam = matris.sum(axis=0) # sutunlarin toplami
    print("Matris:\n", matris)
    print("Satir Toplamlari:\n", satirToplam)
    print("Sutun Toplamlari:\n", sutunToplam)
    break

Matris:
 [[42 23 30 15 35]
 [11 48 11 45 49]
 [42 43 22 19 19]]
Satir Toplamlari:
 [145 164 145]
Sutun Toplamlari:
 [ 95 114  63  79 103]


In [26]:
print(
	f"matris max : {matris.max()}\n"
	f"matris min : {matris.min()}\n"
	f"matris mean : {matris.mean()}\n"
	f"matris std : {matris.std()}"
)

matris max : 49
matris min : 11
matris mean : 30.266666666666666
matris std : 13.398839087357118


In [ ]:
matris.argmax() # en buyuk degerin indexi
matris.argmin() # en kucuk degerin indexi

5

In [30]:
arr =np.arange(10,20)
arr[:3]

array([10, 11, 12])

In [ ]:
arr[::-1] # ters cevirme islemi

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [39]:
matris[0,:] # ilk satiri al
matris[:,0] # ilk sutunu al

array([42, 11, 42])

In [40]:
matris[0]

array([42, 23, 30, 15, 35])

In [41]:
matris[1,2]

11

In [42]:
matris**2

array([[1764,  529,  900,  225, 1225],
       [ 121, 2304,  121, 2025, 2401],
       [1764, 1849,  484,  361,  361]])

In [43]:
result =matris % 2 == 0
print(matris)
print(result)
print('Çift sayılar :',matris[result])

[[42 23 30 15 35]
 [11 48 11 45 49]
 [42 43 22 19 19]]
[[ True False  True False False]
 [False  True False False False]
 [ True False  True False False]]
Çift sayılar : [42 30 48 42 22]
